
gjamPlot <- function(output, plotPars){
  
  # output     - list generated by gjamGibbs
  # plotPars   - list can include 
  #   sdScale=F  - plot posteriors on standardized scale
  #   trueValues - list can include 'beta', 'y', 'cor', 'cuts'
  
  tmp <- .gjamPlot(output, plotPars)
  invisible(tmp)
}
  
