# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.byRccpCpp <- function(nr, frommat, totmat, summat, minmat, maxmat) {
    .Call('gjam_byRccpCpp', PACKAGE = 'gjam', nr, frommat, totmat, summat, minmat, maxmat)
}

.conditionalMVNRcppCpp <- function(cdex, gdex, xx, mu, sigma) {
    .Call('gjam_conditionalMVNRcppCpp', PACKAGE = 'gjam', cdex, gdex, xx, mu, sigma)
}

.tnorm_cpp <- function(lo, hi, mu, sig) {
    .Call('gjam_tnorm_cpp', PACKAGE = 'gjam', lo, hi, mu, sig)
}

.tnormCpp <- function(lo, hi, mu, sig) {
    .Call('gjam_tnormCpp', PACKAGE = 'gjam', lo, hi, mu, sig)
}

.any_naCpp <- function(x) {
    .Call('gjam_any_naCpp', PACKAGE = 'gjam', x)
}

.tnormMVNmatrixRcppCpp <- function(avec, muvec, smat, lo, hi, whichSample, idxALL) {
    .Call('gjam_tnormMVNmatrixRcppCpp', PACKAGE = 'gjam', avec, muvec, smat, lo, hi, whichSample, idxALL)
}

.rmvnormArma <- function(n, mu, sigma) {
    .Call('gjam_rmvnormArma', PACKAGE = 'gjam', n, mu, sigma)
}

.rmatrixnormArma <- function(n, p, M, sigmacols, sigmarows) {
    .Call('gjam_rmatrixnormArma', PACKAGE = 'gjam', n, p, M, sigmacols, sigmarows)
}

.solveArma <- function(A) {
    .Call('gjam_solveArma', PACKAGE = 'gjam', A)
}

.obtainpmatKcpp <- function(pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk) {
    .Call('gjam_obtainpmatKcpp', PACKAGE = 'gjam', pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk)
}

.rmvnormArma2 <- function(n, mu, sigma) {
    .Call('gjam_rmvnormArma2', PACKAGE = 'gjam', n, mu, sigma)
}

.bodyfnZarma <- function(kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz) {
    .Call('gjam_bodyfnZarma', PACKAGE = 'gjam', kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz)
}

.invWoodburryArma <- function(sigsq, A) {
    .Call('gjam_invWoodburryArma', PACKAGE = 'gjam', sigsq, A)
}

