# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

byRccp <- function(nr, frommat, totmat, summat, minmat, maxmat) {
    .Call('gjam_byRccp', PACKAGE = 'gjam', nr, frommat, totmat, summat, minmat, maxmat)
}

byProdRccp <- function(nr, frommat, totmat, prodmat) {
    .Call('gjam_byProdRccp', PACKAGE = 'gjam', nr, frommat, totmat, prodmat)
}

condMVNRcpp <- function(cdex, gdex, xx, mu, sigma) {
    .Call('gjam_condMVNRcpp', PACKAGE = 'gjam', cdex, gdex, xx, mu, sigma)
}

tnorm_cpp <- function(lo, hi, mu, sig) {
    .Call('gjam_tnorm_cpp', PACKAGE = 'gjam', lo, hi, mu, sig)
}

tnormRcpp <- function(lo, hi, mu, sig) {
    .Call('gjam_tnormRcpp', PACKAGE = 'gjam', lo, hi, mu, sig)
}

any_naCpp <- function(x) {
    .Call('gjam_any_naCpp', PACKAGE = 'gjam', x)
}

trMVNmatrixRcpp <- function(avec, muvec, smat, lo, hi, whichSample, idxALL) {
    .Call('gjam_trMVNmatrixRcpp', PACKAGE = 'gjam', avec, muvec, smat, lo, hi, whichSample, idxALL)
}

rmvnormRcpp <- function(n, mu, sigma) {
    .Call('gjam_rmvnormRcpp', PACKAGE = 'gjam', n, mu, sigma)
}

rmatrixnormRcpp <- function(n, p, M, sigmacols, sigmarows) {
    .Call('gjam_rmatrixnormRcpp', PACKAGE = 'gjam', n, p, M, sigmacols, sigmarows)
}

solveRcpp <- function(A) {
    .Call('gjam_solveRcpp', PACKAGE = 'gjam', A)
}

getPmatKRcpp <- function(pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk) {
    .Call('gjam_getPmatKRcpp', PACKAGE = 'gjam', pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk)
}

rmvnormArma2 <- function(n, mu, sigma) {
    .Call('gjam_rmvnormArma2', PACKAGE = 'gjam', n, mu, sigma)
}

fnZRcpp <- function(kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz) {
    .Call('gjam_fnZRcpp', PACKAGE = 'gjam', kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz)
}

invWbyRcpp <- function(sigsq, A) {
    .Call('gjam_invWbyRcpp', PACKAGE = 'gjam', sigsq, A)
}

